# Generated by Django 4.2.1 on 2023-05-24 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_signup_address_signup_pin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signup',
            name='city',
        ),
    ]
